/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practico_7.formularios;

import Practico_7.entidades.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AltaMaterias extends javax.swing.JInternalFrame {
    private HashSet<Materia> materias;
    /**
     * Creates new form FormAlumnos
     */
    public AltaMaterias(HashSet materias) {
        this.materias = materias;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtidMateria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtMateria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtAnio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setTitle("Alta de Materias");
        setPreferredSize(new java.awt.Dimension(400, 300));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jtidMateria.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtidMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidMateriaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Codigo Materia:");

        jtMateria.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMateriaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Nombre de la Materia:");

        jtAnio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAnioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Año al que pertenece:");

        jbGuardar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jbGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbGuardarKeyPressed(evt);
            }
        });

        jbNuevo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jbNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbNuevoKeyPressed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jbSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtAnio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtidMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jbGuardar)
                .addGap(4, 4, 4)
                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtidMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo)
                    .addComponent(jbSalir))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        jtidMateria.setFocusable(true);
        jtidMateria.requestFocusInWindow();
        jtidMateria.requestFocus(true);
        jtidMateria.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jtidMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidMateriaActionPerformed
        jtMateria.setFocusable(true);
        jtMateria.requestFocusInWindow();
        jtMateria.requestFocus(true);
        jtMateria.requestFocus();          // TODO add your handling code here:
    }//GEN-LAST:event_jtidMateriaActionPerformed

    private void jtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMateriaActionPerformed
        jtAnio.setFocusable(true);
        jtAnio.requestFocusInWindow();
        jtAnio.requestFocus(true);
        jtAnio.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_jtMateriaActionPerformed

    private void jtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAnioActionPerformed
        jbGuardar.setFocusable(true);
        jbGuardar.requestFocusInWindow();
        jbGuardar.requestFocus(true);
        jbGuardar.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_jtAnioActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        int idMateria = 0;
        try {
            idMateria = Integer.parseInt(jtidMateria.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,  "Usted no ingresó un nro correcto de código de Materia",
                "ERROR!", JOptionPane.ERROR_MESSAGE);
            jtidMateria.selectAll();
            jtidMateria.setFocusable(true);
            jtidMateria.requestFocusInWindow();
            jtidMateria.requestFocus(true);
            jtidMateria.requestFocus();
            return;
        }
        String materia = jtMateria.getText();
        int espacios = 0;
        for (int i=0;i<materia.length();i++) {
                if (materia.charAt(i)==' ') {
                espacios++;
            }
        }
        if (materia.isEmpty() || espacios==materia.length()) {
            JOptionPane.showMessageDialog(this, "No puede estar vacia la Materia", 
                    "ATENCION!", JOptionPane.WARNING_MESSAGE);
            jtMateria.selectAll();
            jtMateria.setFocusable(true);
            jtMateria.requestFocusInWindow();
            jtMateria.requestFocus(true);
            jtMateria.requestFocus();
            return;
        }
        int anio = 0;
        try {
            anio = Integer.parseInt(jtAnio.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,  "Usted no ingresó un nro correcto de año",
                "ERROR!", JOptionPane.ERROR_MESSAGE);
            jtAnio.selectAll();
            jtAnio.setFocusable(true);
            jtAnio.requestFocusInWindow();
            jtAnio.requestFocus(true);
            jtAnio.requestFocus();
            return;
        }
        int opcion = JOptionPane.showConfirmDialog(null, "Se guardara la Materia\nCódigo: "+idMateria+"\nMateria: "+materia+"\nAño: "+anio,
                "Confirme los datos", JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        switch (opcion) {
            case 0:
                if (materias.add(new Materia(idMateria, materia, anio))){
                jbNuevo.doClick();
                JOptionPane.showMessageDialog(this, "Datos guardados correctamente");
                } else {
                    JOptionPane.showMessageDialog(this,  "La Materia\nCódigo: "+idMateria+"\nMateria: "+materia+"\nAño: "+anio+
                    "\nya está dada de alta",
                    "ERROR!", JOptionPane.ERROR_MESSAGE);
                    jbNuevo.doClick();
                    break;
                }
            case 1:
                jtidMateria.selectAll();
                jtidMateria.setFocusable(true);
                jtidMateria.requestFocusInWindow();
                jtidMateria.requestFocus(true);
                jtidMateria.requestFocus();
                break;
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jtidMateria.setText("");
        jtMateria.setText("");
        jtAnio.setText("");
        jtidMateria.setFocusable(true);
        jtidMateria.requestFocusInWindow();
        jtidMateria.requestFocus(true);
        jtidMateria.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbGuardarKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) jbGuardar.doClick();
    }//GEN-LAST:event_jbGuardarKeyPressed

    private void jbNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbNuevoKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) jbNuevo.doClick();
    }//GEN-LAST:event_jbNuevoKeyPressed

    private void jbSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalirKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) dispose();
    }//GEN-LAST:event_jbSalirKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtAnio;
    private javax.swing.JTextField jtMateria;
    private javax.swing.JTextField jtidMateria;
    // End of variables declaration//GEN-END:variables
}
