/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practico_7.formularios;

import Practico_7.entidades.Alumno;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AltaAlumnos extends javax.swing.JInternalFrame {
    private HashSet <Alumno> alumnos;
    /**
     * Creates new form FormAlumnos
     */
    public AltaAlumnos(HashSet alumnos) {
        this.alumnos = alumnos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtLegajo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setTitle("Alta de Alumnos");
        setPreferredSize(new java.awt.Dimension(400, 300));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jtLegajo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtLegajoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("LEGAJO:");

        jtApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("APELLIDO:");

        jtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("NOMBRE:");

        jbGuardar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jbGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbGuardarKeyPressed(evt);
            }
        });

        jbNuevo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jbNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbNuevoKeyPressed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jbSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbGuardar)
                        .addGap(4, 4, 4)
                        .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(45, 45, 45)
                            .addComponent(jtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtApellido)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo)
                    .addComponent(jbSalir))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        jtLegajo.setFocusable(true);
        jtLegajo.requestFocusInWindow();
        jtLegajo.requestFocus(true);
        jtLegajo.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jtLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtLegajoActionPerformed
        jtApellido.setFocusable(true);
        jtApellido.requestFocusInWindow();
        jtApellido.requestFocus(true);
        jtApellido.requestFocus();          // TODO add your handling code here:
    }//GEN-LAST:event_jtLegajoActionPerformed

    private void jtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellidoActionPerformed
        jtNombre.setFocusable(true);
        jtNombre.requestFocusInWindow();
        jtNombre.requestFocus(true);
        jtNombre.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_jtApellidoActionPerformed

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        jbGuardar.setFocusable(true);
        jbGuardar.requestFocusInWindow();
        jbGuardar.requestFocus(true);
        jbGuardar.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        int legajo = 0;
        try {
            legajo = Integer.parseInt(jtLegajo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,  "Usted no ingresó un nro correcto de legajo",
                "ERROR!", JOptionPane.ERROR_MESSAGE);
            jtLegajo.selectAll();
            jtLegajo.setFocusable(true);
            jtLegajo.requestFocusInWindow();
            jtLegajo.requestFocus(true);
            jtLegajo.requestFocus();
            return;
        }
        String apellido = jtApellido.getText();
        int espacios = 0;
        for (int i=0;i<apellido.length();i++) {
                if (apellido.charAt(i)==' ') {
                espacios++;
            }
        }
        if (apellido.isEmpty() || espacios==apellido.length()) {
            JOptionPane.showMessageDialog(this, "No puede estar vacio el apellido", 
                    "ATENCION!", JOptionPane.WARNING_MESSAGE);
            jtApellido.selectAll();
            jtApellido.setFocusable(true);
            jtApellido.requestFocusInWindow();
            jtApellido.requestFocus(true);
            jtApellido.requestFocus();
            return;
        }
        String nombre = jtNombre.getText();
        for (int i=0;i<nombre.length();i++) {
                if (nombre.charAt(i)==' ') {
                espacios++;
            }
        }
        if (nombre.isEmpty() || espacios==nombre.length()) {
            JOptionPane.showMessageDialog(this, "No puede estar vacio el nombre", 
                    "ATENCION!", JOptionPane.WARNING_MESSAGE);
            jtNombre.selectAll();
            jtNombre.setFocusable(true);
            jtNombre.requestFocusInWindow();
            jtNombre.requestFocus(true);
            jtNombre.requestFocus();
            return;
        }
        int opcion = JOptionPane.showConfirmDialog(null, "Se guardara el Alumno\nLegajo: "+legajo+"\nNombre: "+apellido+", "+nombre,
                "Confirme los datos", JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        switch (opcion) {
            case 0:
                if (alumnos.add(new Alumno(legajo, apellido, nombre))){
                    jbNuevo.doClick();
                    JOptionPane.showMessageDialog(this, "Datos guardados correctamente");
                } else {
                    JOptionPane.showMessageDialog(this,  "El alumno\nLegajo: "+legajo+"\nNombre: "+apellido+", "+nombre+
                    "\nya está dado de alta",
                    "ERROR!", JOptionPane.ERROR_MESSAGE);
                    jbNuevo.doClick();
                }
            break;
            case 1:
                jtLegajo.selectAll();
                jtLegajo.setFocusable(true);
                jtLegajo.requestFocusInWindow();
                jtLegajo.requestFocus(true);
                jtLegajo.requestFocus();
                break;
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jtLegajo.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
        jtLegajo.setFocusable(true);
        jtLegajo.requestFocusInWindow();
        jtLegajo.requestFocus(true);
        jtLegajo.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbGuardarKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) jbGuardar.doClick();
    }//GEN-LAST:event_jbGuardarKeyPressed

    private void jbNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbNuevoKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) jbNuevo.doClick();
    }//GEN-LAST:event_jbNuevoKeyPressed

    private void jbSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalirKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) dispose();
    }//GEN-LAST:event_jbSalirKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtLegajo;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
