/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practico_7.formularios;

import Practico_7.entidades.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FormInscripcion extends javax.swing.JInternalFrame {
    private HashSet <Alumno> alumnos;
    private HashSet <Materia> materias;
    /**
     * Creates new form FormInscripcion
     */
    public FormInscripcion(HashSet alumnos, HashSet materias) {
        this.alumnos = alumnos;
        this.materias = materias;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jbInscribir = new javax.swing.JButton();
        jcbMateria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcbAlumno = new javax.swing.JComboBox<>();

        setTitle("Formulario de inscripción");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("ELIJA UN ALUMNO:");

        jbSalir.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jbSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalirKeyPressed(evt);
            }
        });

        jbInscribir.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });
        jbInscribir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbInscribirKeyPressed(evt);
            }
        });

        jcbMateria.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jcbMateria.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("ELIJA UNA MATERIA:");

        jcbAlumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jbInscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbInscribir))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        if (alumnos.size()>0) {
            
            for (Iterator it = alumnos.iterator();it.hasNext();) {
                jcbAlumno.addItem((Alumno) it.next());
            }
        }
        if (materias.size()>0) {
            for (Iterator it = materias.iterator();it.hasNext();) {
                jcbMateria.addItem((Materia) it.next());
            }
        }
   
    }//GEN-LAST:event_formFocusGained

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalirKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) dispose();
    }//GEN-LAST:event_jbSalirKeyPressed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        Materia materia = (Materia)jcbMateria.getSelectedItem();
        Alumno alumno = (Alumno)jcbAlumno.getSelectedItem();
        if (alumno.getMaterias().contains(materia)) {
            JOptionPane.showMessageDialog(this,  "El alumno:\n"+jcbAlumno.getSelectedItem()+
                    "\nya tiene asignada la materia:\n"+jcbMateria.getSelectedItem(),
                    "ERROR!", JOptionPane.ERROR_MESSAGE);
            jcbMateria.setFocusable(true);
            jcbMateria.requestFocusInWindow();
            jcbMateria.requestFocus(true);
            jcbMateria.requestFocus();
            return;            
        } else {
            alumno.agregarMateria(materia);
            JOptionPane.showMessageDialog(this, "Se asignó correctamente\nla materia: "+
                    jcbMateria.getSelectedItem()+"\npara el Alumno: "+jcbAlumno.getSelectedItem());
        }

    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbInscribirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbInscribirKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) jbInscribir.doClick();
    }//GEN-LAST:event_jbInscribirKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Alumno> jcbAlumno;
    private javax.swing.JComboBox<Materia> jcbMateria;
    // End of variables declaration//GEN-END:variables
}
